import {
  getPermissionsForRole,
  type Permission,
  type Role,
} from "@/lib/permissions";

export type BuiltInRoleModule =
  | "core"
  | "dawa"
  | "retail"
  | "hardware"
  | "hospitality"
  | "salon";

export interface BuiltInRoleDefinition {
  id: string;
  name: string;
  module: BuiltInRoleModule;
  moduleLabel: string;
  description: string;
  legacyRole: Role;
  permissions: readonly Permission[];
  searchTerms: readonly string[];
}

const VERTICAL_PREFIXES = [
  "pharmacy.",
  "retail.",
  "hardware.",
  "hospitality.",
  "salon.",
] as const;

const VERTICAL_STANDALONE_PERMISSIONS = new Set<Permission>([
  "claims.view",
  "claims.submit",
  "promotions.manage",
  "loyalty.manage",
]);

function unique(...groups: ReadonlyArray<readonly Permission[]>): Permission[] {
  return [...new Set(groups.flat())];
}

function corePermissions(role: Role): Permission[] {
  return getPermissionsForRole(role).filter(
    (permission) =>
      !VERTICAL_PREFIXES.some((prefix) => permission.startsWith(prefix)) &&
      !VERTICAL_STANDALONE_PERMISSIONS.has(permission),
  );
}

const CORE_CASHIER = corePermissions("cashier");
const CORE_MANAGER = corePermissions("manager");
const CORE_VIEWER = corePermissions("viewer");

/**
 * Maintained job roles shown to owners when they add or edit staff.
 *
 * IDs are stable database contracts. Never rename an ID after release. The
 * legacyRole remains in users.role as a safe fallback for old installations;
 * the richer permission set is resolved through user_roles when available.
 */
export const BUILT_IN_ROLES = [
  {
    id: "role_owner",
    name: "Business Owner",
    module: "core",
    moduleLabel: "Core",
    description: "Complete access to the business, staff, licences, settings, and every enabled module.",
    legacyRole: "owner",
    permissions: getPermissionsForRole("owner"),
    searchTerms: ["admin", "proprietor", "director", "full access"],
  },
  {
    id: "role_manager",
    name: "General Manager",
    module: "core",
    moduleLabel: "Core",
    description: "Runs daily operations, stock, purchasing, finance, and reports without owner-only administration.",
    legacyRole: "manager",
    permissions: getPermissionsForRole("manager"),
    searchTerms: ["operations", "supervisor", "branch manager"],
  },
  {
    id: "role_core_branch_manager",
    name: "Branch Manager",
    module: "core",
    moduleLabel: "Core",
    description: "Runs one location's sales, stock, purchasing, expenses, staff attendance, and operating reports.",
    legacyRole: "manager",
    permissions: CORE_MANAGER,
    searchTerms: ["location manager", "shop manager", "operations manager"],
  },
  {
    id: "role_core_sales_supervisor",
    name: "Sales Supervisor",
    module: "core",
    moduleLabel: "Core",
    description: "Supervises tills and customers, reviews sales, approves refunds, and follows invoices and targets.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "sales.refund",
      "sales.void",
      "reports.view",
      "invoicing.view",
      "invoicing.create",
      "invoicing.send",
      "invoicing.payment",
    ]),
    searchTerms: ["head cashier", "till supervisor", "sales lead", "floor manager"],
  },
  {
    id: "role_core_procurement",
    name: "Procurement Officer",
    module: "core",
    moduleLabel: "Core",
    description: "Maintains suppliers, prepares purchase orders, follows deliveries, and reviews purchasing records.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "purchase_orders.create",
      "purchase_orders.receive",
      "suppliers.edit",
      "suppliers.payment",
    ]),
    searchTerms: ["buyer", "purchasing", "sourcing", "supply chain"],
  },
  {
    id: "role_core_receiving",
    name: "Goods Receiving & Warehouse Clerk",
    module: "core",
    moduleLabel: "Core",
    description: "Receives deliveries, checks supplier documents, updates stock, records damage, and supports stock counts.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "inventory.edit",
      "purchase_orders.receive",
      "stock_take.use",
    ]),
    searchTerms: ["goods received", "warehouse", "receiving clerk", "storekeeper"],
  },
  {
    id: "role_core_accountant",
    name: "Accountant",
    module: "core",
    moduleLabel: "Core",
    description: "Manages banking, reconciliations, expenses, receivables, payables, invoices, and financial statements.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "expenses.create",
      "customers.payment",
      "suppliers.payment",
      "petty_cash.use",
      "invoicing.view",
      "invoicing.create",
      "invoicing.send",
      "invoicing.payment",
      "invoicing.cancel",
      "banking.view",
      "banking.manage",
      "banking.reconcile",
      "reports.zreport",
    ]),
    searchTerms: ["finance manager", "financial accountant", "general ledger", "reconciliation"],
  },
  {
    id: "role_core_receivables",
    name: "Accounts Receivable Clerk",
    module: "core",
    moduleLabel: "Core",
    description: "Maintains customer accounts, issues invoices, records incoming payments, and follows outstanding balances.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "customers.edit",
      "customers.payment",
      "invoicing.view",
      "invoicing.create",
      "invoicing.send",
      "invoicing.payment",
      "banking.view",
    ]),
    searchTerms: ["credit control", "debtors", "collections", "customer accounts"],
  },
  {
    id: "role_core_payables",
    name: "Accounts Payable Clerk",
    module: "core",
    moduleLabel: "Core",
    description: "Maintains suppliers, records expenses and supplier payments, and checks outgoing bank transactions.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "suppliers.edit",
      "suppliers.payment",
      "purchase_orders.view",
      "expenses.create",
      "banking.view",
    ]),
    searchTerms: ["creditors", "supplier accounts", "payments clerk", "expenses"],
  },
  {
    id: "role_core_hr_manager",
    name: "HR Manager",
    module: "core",
    moduleLabel: "Core",
    description: "Manages employee records, attendance, leave, payroll preparation, approvals, and people reports.",
    legacyRole: "viewer",
    permissions: [
      "users.view",
      "hr.employees.view",
      "hr.employees.manage",
      "hr.payroll.view",
      "hr.payroll.run",
      "hr.payroll.approve",
      "hr.attendance.view",
      "hr.attendance.record",
      "hr.leave.request",
      "hr.leave.approve",
      "reports.view",
    ],
    searchTerms: ["human resources", "people manager", "personnel", "hr administrator"],
  },
  {
    id: "role_core_payroll",
    name: "Payroll Officer",
    module: "core",
    moduleLabel: "Core",
    description: "Reviews employee and attendance records, prepares payroll, and submits payroll for approval.",
    legacyRole: "viewer",
    permissions: [
      "hr.employees.view",
      "hr.payroll.view",
      "hr.payroll.run",
      "hr.attendance.view",
      "reports.view",
      "banking.view",
    ],
    searchTerms: ["payroll clerk", "wages", "salary", "payslips"],
  },
  {
    id: "role_core_attendance",
    name: "Attendance & Leave Officer",
    module: "core",
    moduleLabel: "Core",
    description: "Maintains attendance, records shifts, reviews leave requests, and keeps employee schedules accurate.",
    legacyRole: "viewer",
    permissions: [
      "hr.employees.view",
      "hr.attendance.view",
      "hr.attendance.record",
      "hr.leave.request",
      "hr.leave.approve",
    ],
    searchTerms: ["timekeeper", "roster", "leave administrator", "shift supervisor"],
  },
  {
    id: "role_core_compliance",
    name: "Tax & Compliance Officer",
    module: "core",
    moduleLabel: "Core",
    description: "Monitors eTIMS submissions, VAT and compliance reports, audit history, and supporting sales records.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "etims.submit",
      "audit.view",
      "reports.zreport",
    ]),
    searchTerms: ["etims", "kra", "vat", "tax officer", "compliance"],
  },
  {
    id: "role_core_system_admin",
    name: "System & Backup Administrator",
    module: "core",
    moduleLabel: "Core",
    description: "Manages staff access, network setup, backups, modules, licences, and the audit log without business finance access.",
    legacyRole: "viewer",
    permissions: [
      "users.view",
      "users.manage",
      "settings.network",
      "settings.backup",
      "settings.modules",
      "license.view",
      "audit.view",
    ],
    searchTerms: ["it admin", "technical support", "network", "backup administrator"],
  },
  {
    id: "role_cashier",
    name: "Cashier",
    module: "core",
    moduleLabel: "Core",
    description: "Sells at the counter, works with customers, handles the cash register, and closes a shift.",
    legacyRole: "cashier",
    permissions: getPermissionsForRole("cashier"),
    searchTerms: ["till", "sales clerk", "counter", "pos"],
  },
  {
    id: "role_core_inventory",
    name: "Inventory & Purchasing Clerk",
    module: "core",
    moduleLabel: "Core",
    description: "Maintains products and suppliers, raises purchase orders, receives stock, and runs stock takes.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "inventory.edit",
      "inventory.bulk_edit",
      "purchase_orders.view",
      "purchase_orders.create",
      "purchase_orders.receive",
      "stock_take.use",
      "suppliers.edit",
    ]),
    searchTerms: ["storekeeper", "stock controller", "procurement", "receiving"],
  },
  {
    id: "role_core_bookkeeper",
    name: "Bookkeeper",
    module: "core",
    moduleLabel: "Core",
    description: "Records expenses and payments, manages invoices and banking, and reviews financial reports.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "expenses.create",
      "customers.payment",
      "suppliers.payment",
      "cash_register.use",
      "petty_cash.use",
      "invoicing.view",
      "invoicing.create",
      "invoicing.send",
      "invoicing.payment",
      "banking.view",
      "banking.manage",
      "banking.reconcile",
    ]),
    searchTerms: ["accounts", "accountant", "finance", "billing"],
  },
  {
    id: "role_viewer",
    name: "Read-only Auditor",
    module: "core",
    moduleLabel: "Core",
    description: "Can inspect sales, stock, expenses, compliance, and reports without changing records.",
    legacyRole: "viewer",
    permissions: getPermissionsForRole("viewer"),
    searchTerms: ["viewer", "auditor", "read only", "oversight"],
  },

  {
    id: "role_dawa_pharmacist_in_charge",
    name: "Pharmacist in Charge",
    module: "dawa",
    moduleLabel: "Pharmacy",
    description: "Leads dispensing, controlled medicines, prescribers, claims, compliance, stock, and pharmacy reports.",
    legacyRole: "manager",
    permissions: unique(CORE_MANAGER, [
      "pharmacy.dispense",
      "pharmacy.refill",
      "pharmacy.controlled",
      "pharmacy.doctors.manage",
      "claims.view",
      "claims.submit",
    ]),
    searchTerms: ["superintendent", "pharmacy manager", "pic", "controlled drugs"],
  },
  {
    id: "role_dawa_pharmacist",
    name: "Pharmacist",
    module: "dawa",
    moduleLabel: "Pharmacy",
    description: "Dispenses prescriptions and controlled medicines, processes refills, and works with claims.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "pharmacy.dispense",
      "pharmacy.refill",
      "pharmacy.controlled",
      "pharmacy.doctors.manage",
      "claims.view",
      "claims.submit",
      "etims.view",
      "etims.submit",
    ]),
    searchTerms: ["chemist", "dispenser", "prescriptions", "controlled medicines"],
  },
  {
    id: "role_dawa_assistant",
    name: "Pharmacy Assistant",
    module: "dawa",
    moduleLabel: "Pharmacy",
    description: "Handles counter sales, customer records, ordinary dispensing, refills, and stock lookup.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, ["pharmacy.access", "pharmacy.dispense", "pharmacy.refill"]),
    searchTerms: ["counter assistant", "pharmaceutical technologist", "sales"],
  },
  {
    id: "role_dawa_cashier",
    name: "Pharmacy Cashier",
    module: "dawa",
    moduleLabel: "Pharmacy",
    description: "Handles pharmacy checkout, customer payments, the cash register, and shift closing without dispensing authority.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, ["pharmacy.access"]),
    searchTerms: ["till", "checkout", "counter cashier", "payments"],
  },
  {
    id: "role_dawa_stock_expiry",
    name: "Pharmacy Stock & Expiry Clerk",
    module: "dawa",
    moduleLabel: "Pharmacy",
    description: "Maintains medicine stock, receiving, batch expiry checks, suppliers, and stock counts without dispensing.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "pharmacy.access",
      "inventory.edit",
      "purchase_orders.create",
      "purchase_orders.receive",
      "stock_take.use",
      "suppliers.edit",
    ]),
    searchTerms: ["storekeeper", "expiry", "batches", "receiving", "inventory"],
  },
  {
    id: "role_dawa_controlled",
    name: "Controlled Medicines Officer",
    module: "dawa",
    moduleLabel: "Pharmacy",
    description: "Dispenses and records controlled medicines, maintains prescribers, and reviews the controlled register.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "pharmacy.access",
      "pharmacy.dispense",
      "pharmacy.controlled",
      "pharmacy.doctors.manage",
      "audit.view",
    ]),
    searchTerms: ["controlled drugs", "narcotics", "register", "compliance pharmacist"],
  },
  {
    id: "role_dawa_claims",
    name: "Claims & Insurance Clerk",
    module: "dawa",
    moduleLabel: "Pharmacy",
    description: "Maintains patient details and prepares, submits, and follows up insurance claims.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "customers.edit",
      "customers.payment",
      "claims.view",
      "claims.submit",
    ]),
    searchTerms: ["sha", "insurance", "medical claims", "billing"],
  },

  {
    id: "role_retail_supervisor",
    name: "Retail Supervisor",
    module: "retail",
    moduleLabel: "Retail",
    description: "Runs the shop floor, stock, pricing, promotions, loyalty, laybys, and daily reports.",
    legacyRole: "manager",
    permissions: unique(CORE_MANAGER, [
      "retail.brands.manage",
      "retail.variants.manage",
      "retail.price_lists.manage",
      "retail.shrinkage.record",
      "retail.laybys.use",
      "retail.special_orders.use",
      "promotions.manage",
      "loyalty.manage",
    ]),
    searchTerms: ["shop manager", "store manager", "floor supervisor"],
  },
  {
    id: "role_retail_sales",
    name: "Retail Cashier & Sales Assistant",
    module: "retail",
    moduleLabel: "Retail",
    description: "Runs the till, serves customers, and manages laybys and special orders from the Retail module.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "retail.access",
      "retail.laybys.use",
      "retail.special_orders.use",
    ]),
    searchTerms: ["shop assistant", "attendant", "cashier", "sales clerk", "checkout"],
  },
  {
    id: "role_retail_customer_service",
    name: "Retail Customer Service & Returns",
    module: "retail",
    moduleLabel: "Retail",
    description: "Handles customer records, returns, refunds, loyalty enquiries, laybys, and special-order follow-up.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "retail.access",
      "sales.refund",
      "retail.laybys.use",
      "retail.special_orders.use",
      "loyalty.manage",
    ]),
    searchTerms: ["returns desk", "refunds", "customer care", "service desk"],
  },
  {
    id: "role_retail_merchandising",
    name: "Merchandising & Pricing Clerk",
    module: "retail",
    moduleLabel: "Retail",
    description: "Maintains brands, product variants, price lists, promotions, and shop-floor product information.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "retail.access",
      "inventory.edit",
      "retail.brands.manage",
      "retail.variants.manage",
      "retail.price_lists.manage",
      "promotions.manage",
    ]),
    searchTerms: ["merchandiser", "pricing", "catalogue", "shelf labels", "promotions"],
  },
  {
    id: "role_retail_stock",
    name: "Retail Stock Controller",
    module: "retail",
    moduleLabel: "Retail",
    description: "Controls receiving, product variants, brands, stock counts, and recorded shrinkage.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "inventory.edit",
      "inventory.bulk_edit",
      "purchase_orders.view",
      "purchase_orders.create",
      "purchase_orders.receive",
      "stock_take.use",
      "suppliers.edit",
      "retail.brands.manage",
      "retail.variants.manage",
      "retail.shrinkage.record",
    ]),
    searchTerms: ["storekeeper", "receiving", "warehouse", "inventory"],
  },
  {
    id: "role_retail_loyalty",
    name: "Loyalty & Promotions Clerk",
    module: "retail",
    moduleLabel: "Retail",
    description: "Maintains customer profiles, loyalty activity, promotions, and assisted sales.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, ["promotions.manage", "loyalty.manage"]),
    searchTerms: ["customer service", "marketing", "rewards", "campaigns"],
  },

  {
    id: "role_hardware_supervisor",
    name: "Hardware Store Supervisor",
    module: "hardware",
    moduleLabel: "Hardware & Equipment",
    description: "Runs counter sales, quotations, delivery notes, contractor credit, equipment, pricing, and reports.",
    legacyRole: "manager",
    permissions: unique(CORE_MANAGER, [
      "hardware.quotations.manage",
      "hardware.delivery_notes.manage",
      "hardware.accounts.manage",
      "hardware.pricing.manage",
      "hardware.commissions.view",
      "hardware.reports.view",
      "hardware.equipment.manage",
    ]),
    searchTerms: ["hardware manager", "yard supervisor", "branch manager"],
  },
  {
    id: "role_hardware_counter_sales",
    name: "Hardware Cashier & Counter Sales",
    module: "hardware",
    moduleLabel: "Hardware & Equipment",
    description: "Runs checkout, serves the counter, prepares quotations, confirms customers, and raises delivery notes.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "hardware.access",
      "hardware.quotations.manage",
      "hardware.delivery_notes.manage",
    ]),
    searchTerms: ["salesperson", "quotation clerk", "counter", "estimator", "cashier"],
  },
  {
    id: "role_hardware_dispatch",
    name: "Yard & Dispatch Clerk",
    module: "hardware",
    moduleLabel: "Hardware & Equipment",
    description: "Checks stock, prepares delivery notes, releases goods, and follows equipment and customer collections.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "hardware.access",
      "inventory.edit",
      "hardware.delivery_notes.manage",
      "hardware.equipment.manage",
    ]),
    searchTerms: ["yard clerk", "dispatch", "loading", "delivery", "collections"],
  },
  {
    id: "role_hardware_service",
    name: "Workshop & Service Technician",
    module: "hardware",
    moduleLabel: "Hardware & Equipment",
    description: "Tracks serialized equipment, warranty work, service jobs, repairs, and rental-unit condition.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "hardware.access",
      "inventory.edit",
      "hardware.equipment.manage",
    ]),
    searchTerms: ["technician", "mechanic", "repair", "workshop", "warranty"],
  },
  {
    id: "role_hardware_accounts",
    name: "Contractor Accounts Clerk",
    module: "hardware",
    moduleLabel: "Hardware & Equipment",
    description: "Maintains contractor credit, customer payments, trade pricing, invoices, and account records.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "customers.edit",
      "customers.payment",
      "hardware.accounts.manage",
      "hardware.pricing.manage",
      "invoicing.view",
      "invoicing.create",
      "invoicing.send",
      "invoicing.payment",
      "banking.view",
    ]),
    searchTerms: ["credit controller", "contractors", "receivables", "accounts"],
  },
  {
    id: "role_hardware_equipment",
    name: "Equipment & Rentals Clerk",
    module: "hardware",
    moduleLabel: "Hardware & Equipment",
    description: "Tracks serialized units, warranty, service, rentals, stock movement, and delivery status.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "inventory.edit",
      "customers.edit",
      "hardware.delivery_notes.manage",
      "hardware.equipment.manage",
    ]),
    searchTerms: ["rental clerk", "fleet", "warranty", "service desk", "serials"],
  },

  {
    id: "role_hospitality_manager",
    name: "Restaurant & Hotel Manager",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Runs service, kitchen, menu, recipes, bookings, rooms, folios, housekeeping, and reports.",
    legacyRole: "manager",
    permissions: unique(CORE_MANAGER, [
      "hospitality.access",
      "hospitality.tables.manage",
      "hospitality.orders.take",
      "hospitality.orders.send_kitchen",
      "hospitality.orders.void",
      "hospitality.kitchen.bump",
      "hospitality.menu.manage",
      "hospitality.recipes.manage",
      "hospitality.bookings.manage",
      "hospitality.checkin.manage",
      "hospitality.folios.manage",
      "hospitality.housekeeping.manage",
      "hospitality.service_charge.manage",
      "hospitality.reports.view",
    ]),
    searchTerms: ["restaurant manager", "hotel manager", "duty manager", "f&b"],
  },
  {
    id: "role_hospitality_restaurant_supervisor",
    name: "Restaurant Supervisor",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Supervises tables and orders, handles voids and refunds, monitors the kitchen, and reviews service reports.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "hospitality.access",
      "hospitality.tables.manage",
      "hospitality.orders.take",
      "hospitality.orders.send_kitchen",
      "hospitality.orders.void",
      "hospitality.kitchen.bump",
      "hospitality.reports.view",
      "sales.refund",
    ]),
    searchTerms: ["shift manager", "floor supervisor", "restaurant lead", "duty supervisor"],
  },
  {
    id: "role_hospitality_cashier",
    name: "Hospitality Cashier",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Handles restaurant or hotel checkout, guest payments, the cash register, orders, and shift closing.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "hospitality.access",
      "hospitality.orders.take",
      "hospitality.orders.send_kitchen",
    ]),
    searchTerms: ["till", "checkout", "restaurant cashier", "hotel cashier"],
  },
  {
    id: "role_hospitality_kitchen_supervisor",
    name: "Chef & Kitchen Supervisor",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Runs kitchen tickets, menu and recipe setup, ingredient stock, food preparation, and kitchen reporting.",
    legacyRole: "viewer",
    permissions: [
      "hospitality.access",
      "hospitality.kitchen.bump",
      "hospitality.menu.manage",
      "hospitality.recipes.manage",
      "hospitality.reports.view",
      "inventory.view",
      "inventory.edit",
    ],
    searchTerms: ["head chef", "kitchen manager", "executive chef", "food production"],
  },
  {
    id: "role_hospitality_reservations",
    name: "Reservations Agent",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Maintains guest records, room availability, reservations, booking changes, and arrival details.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "hospitality.access",
      "customers.edit",
      "hospitality.bookings.manage",
      "hospitality.checkin.manage",
    ]),
    searchTerms: ["booking agent", "reservations clerk", "guest services", "front office"],
  },
  {
    id: "role_hospitality_housekeeping_supervisor",
    name: "Housekeeping Supervisor",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Assigns and checks room work, updates room readiness, monitors supplies, and reviews housekeeping status.",
    legacyRole: "viewer",
    permissions: [
      "hospitality.access",
      "hospitality.housekeeping.manage",
      "hospitality.reports.view",
      "inventory.view",
      "inventory.edit",
    ],
    searchTerms: ["executive housekeeper", "rooms supervisor", "laundry supervisor", "cleaning lead"],
  },
  {
    id: "role_hospitality_front_of_house",
    name: "Waiter & Front of House",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Opens tables, takes orders, sends tickets to the kitchen, serves guests, and takes payment.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, [
      "hospitality.tables.manage",
      "hospitality.orders.take",
      "hospitality.orders.send_kitchen",
    ]),
    searchTerms: ["waiter", "server", "bartender", "floor staff", "foh"],
  },
  {
    id: "role_hospitality_kitchen",
    name: "Kitchen Staff",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Reads kitchen tickets, advances prepared items, and checks ingredient stock without seeing finance.",
    legacyRole: "viewer",
    permissions: ["inventory.view", "hospitality.kitchen.bump"],
    searchTerms: ["chef", "cook", "kds", "kitchen display", "bar"],
  },
  {
    id: "role_hospitality_reception",
    name: "Front Desk & Reception",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Manages guests, room bookings, check-in and check-out, folios, and guest payments.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "customers.edit",
      "customers.payment",
      "hospitality.bookings.manage",
      "hospitality.checkin.manage",
      "hospitality.folios.manage",
    ]),
    searchTerms: ["receptionist", "reservations", "hotel front desk", "guest services"],
  },
  {
    id: "role_hospitality_housekeeping",
    name: "Housekeeping",
    module: "hospitality",
    moduleLabel: "Hospitality",
    description: "Views room work and updates cleaning, inspection, and room-readiness status only.",
    legacyRole: "viewer",
    permissions: ["hospitality.housekeeping.manage"],
    searchTerms: ["room attendant", "cleaner", "laundry", "maintenance"],
  },

  {
    id: "role_salon_manager",
    name: "Salon & Spa Manager",
    module: "salon",
    moduleLabel: "Salon & Spa",
    description: "Runs appointments, services, staff skills, commissions, stock, checkout, and performance reports.",
    legacyRole: "manager",
    permissions: unique(CORE_MANAGER, [
      "salon.appointments.manage",
      "salon.services.manage",
      "salon.staff.manage",
      "salon.reports.view",
    ]),
    searchTerms: ["spa manager", "salon owner", "branch manager"],
  },
  {
    id: "role_salon_reception",
    name: "Salon Receptionist",
    module: "salon",
    moduleLabel: "Salon & Spa",
    description: "Books appointments, maintains client details, checks clients out, and handles the front desk.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, ["salon.access", "salon.appointments.manage"]),
    searchTerms: ["front desk", "booking", "client care", "reception"],
  },
  {
    id: "role_salon_cashier",
    name: "Salon Cashier",
    module: "salon",
    moduleLabel: "Salon & Spa",
    description: "Opens the Salon module, checks clients out, receives payments, manages the till, and closes shifts.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, ["salon.access", "salon.appointments.manage"]),
    searchTerms: ["checkout", "till", "payments", "front counter"],
  },
  {
    id: "role_salon_staff_commissions",
    name: "Salon Staff & Commissions Coordinator",
    module: "salon",
    moduleLabel: "Salon & Spa",
    description: "Maintains salon staff, skills, rosters, attendance, commissions, and staff performance reports.",
    legacyRole: "viewer",
    permissions: [
      "salon.access",
      "salon.staff.manage",
      "salon.reports.view",
      "hr.employees.view",
      "hr.attendance.view",
      "hr.attendance.record",
    ],
    searchTerms: ["commission manager", "roster", "staff coordinator", "people admin"],
  },
  {
    id: "role_salon_stylist",
    name: "Stylist & Therapist",
    module: "salon",
    moduleLabel: "Salon & Spa",
    description: "Views and updates assigned appointments, completes checkout, checks stock, and records attendance.",
    legacyRole: "cashier",
    permissions: unique(CORE_CASHIER, ["salon.appointments.manage"]),
    searchTerms: ["barber", "beautician", "nail technician", "massage therapist"],
  },
  {
    id: "role_salon_services_stock",
    name: "Services & Stock Coordinator",
    module: "salon",
    moduleLabel: "Salon & Spa",
    description: "Maintains the service catalogue, back-bar stock, suppliers, receiving, and stock counts.",
    legacyRole: "viewer",
    permissions: unique(CORE_VIEWER, [
      "inventory.edit",
      "purchase_orders.view",
      "purchase_orders.create",
      "purchase_orders.receive",
      "stock_take.use",
      "suppliers.edit",
      "salon.services.manage",
    ]),
    searchTerms: ["storekeeper", "service coordinator", "back bar", "inventory"],
  },
] as const satisfies readonly BuiltInRoleDefinition[];

export type BuiltInRoleId = (typeof BUILT_IN_ROLES)[number]["id"];

export const BUILT_IN_ROLE_IDS: readonly BuiltInRoleId[] = BUILT_IN_ROLES.map(
  (role) => role.id,
);

export const LEGACY_SYSTEM_ROLE_IDS = [
  "role_owner",
  "role_manager",
  "role_cashier",
  "role_viewer",
] as const satisfies readonly BuiltInRoleId[];

export function builtInRoleById(id: string | null | undefined): BuiltInRoleDefinition | null {
  return BUILT_IN_ROLES.find((role) => role.id === id) ?? null;
}

export function defaultBuiltInRoleId(role: Role): BuiltInRoleId {
  return `role_${role}` as BuiltInRoleId;
}

export function isBuiltInRoleId(value: string): value is BuiltInRoleId {
  return BUILT_IN_ROLE_IDS.includes(value as BuiltInRoleId);
}
