-- Phase 8: LAN multi-device

-- Stores network mode + master endpoint when in client mode.
-- (key/value pairs in settings table; documented here for reference)
--   network.mode = 'standalone' | 'master' | 'client'
--   network.master_url = 'http://192.168.1.x:8765'   (client mode only)
--   network.master_token = '<bearer token>'           (client mode only)
--   network.server_port = '8765'                       (master mode)
--   network.device_name = 'Front Counter PC'

-- API tokens for paired devices (master device issues these)
CREATE TABLE IF NOT EXISTS api_tokens (
    token TEXT PRIMARY KEY,                   -- bearer token (random)
    device_name TEXT NOT NULL,
    device_fingerprint TEXT,                   -- machine fingerprint of the client
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_seen_at TEXT,
    revoked INTEGER NOT NULL DEFAULT 0
);

-- Pairing codes (short-lived 6-digit codes generated by master)
CREATE TABLE IF NOT EXISTS pairing_codes (
    code TEXT PRIMARY KEY,                     -- 6-digit code
    expires_at TEXT NOT NULL,
    used_at TEXT,
    issued_token TEXT REFERENCES api_tokens(token),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_api_tokens_revoked ON api_tokens(revoked);
CREATE INDEX IF NOT EXISTS idx_pairing_codes_expires ON pairing_codes(expires_at);
