/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    licenses: License;
    machines: Machine;
    activations: Activation;
    releases: Release;
    'telemetry-events': TelemetryEvent;
    payments: Payment;
    'support-tickets': SupportTicket;
    pages: Page;
    'blog-posts': BlogPost;
    modules: Module;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    licenses: LicensesSelect<false> | LicensesSelect<true>;
    machines: MachinesSelect<false> | MachinesSelect<true>;
    activations: ActivationsSelect<false> | ActivationsSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    'telemetry-events': TelemetryEventsSelect<false> | TelemetryEventsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'support-tickets': SupportTicketsSelect<false> | SupportTicketsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    pricing: Pricing;
    'landing-page': LandingPage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Internal staff accounts (owner + support). Customers live in the Customers collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'owner' | 'support';
  /**
   * Optional. For internal contact only.
   */
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Customer accounts — anyone with a Omnix license or trial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName: string;
  /**
   * e.g. "Mama Mary's Pharmacy"
   */
  businessName: string;
  /**
   * +254 7XX XXX XXX
   */
  phone: string;
  /**
   * Optional second number. Same format as phone.
   */
  whatsapp?: string | null;
  /**
   * Optional but recommended. Letters then digits, e.g. P051234567A.
   */
  kraPin?: string | null;
  country?: string | null;
  county?:
    | (
        | 'baringo'
        | 'bomet'
        | 'bungoma'
        | 'busia'
        | 'elgeyo-marakwet'
        | 'embu'
        | 'garissa'
        | 'homa-bay'
        | 'isiolo'
        | 'kajiado'
        | 'kakamega'
        | 'kericho'
        | 'kiambu'
        | 'kilifi'
        | 'kirinyaga'
        | 'kisii'
        | 'kisumu'
        | 'kitui'
        | 'kwale'
        | 'laikipia'
        | 'lamu'
        | 'machakos'
        | 'makueni'
        | 'mandera'
        | 'marsabit'
        | 'meru'
        | 'migori'
        | 'mombasa'
        | 'muranga'
        | 'nairobi'
        | 'nakuru'
        | 'nandi'
        | 'narok'
        | 'nyamira'
        | 'nyandarua'
        | 'nyeri'
        | 'samburu'
        | 'siaya'
        | 'taita-taveta'
        | 'tana-river'
        | 'tharaka-nithi'
        | 'trans-nzoia'
        | 'turkana'
        | 'uasin-gishu'
        | 'vihiga'
        | 'wajir'
        | 'west-pokot'
      )
    | null;
  town?: string | null;
  physicalAddress?: string | null;
  businessType?: ('pharmacy' | 'mini_mart' | 'duka' | 'restaurant' | 'hardware' | 'other') | null;
  employeeCount?: ('1' | '2-5' | '6-15' | '16-50' | '50+') | null;
  howDidYouHear?: ('google' | 'friend' | 'social' | 'reseller' | 'other') | null;
  newsletterOptIn?: boolean | null;
  /**
   * Updated automatically on dashboard activity.
   */
  lastSeenAt?: string | null;
  status?: ('active' | 'suspended' | 'banned') | null;
  /**
   * Owner-only notes. Never visible to the customer.
   */
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * License entitlements. One customer can hold many.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses".
 */
export interface License {
  id: number;
  /**
   * Auto-generated on creation. Format: OMNIX-XXXX-XXXX-XXXX. Read-only after create.
   */
  licenseKey?: string | null;
  customer: number | Customer;
  tier: 'trial' | 'starter' | 'business' | 'enterprise';
  modules: ('core' | 'dawa' | 'retail' | 'hardware' | 'hospitality')[];
  maxBranches?: number | null;
  /**
   * Number of PCs that can activate with this license key.
   */
  maxMachines?: number | null;
  /**
   * Max self-service machine rebinds allowed within rebindWindowDays. 0 = support-only.
   */
  rebindLimitPerWindow?: number | null;
  /**
   * Rolling window (days) over which rebindLimitPerWindow is counted.
   */
  rebindWindowDays?: number | null;
  /**
   * Rebinds used in the current window. Reset when the window rolls over.
   */
  rebindCountInWindow?: number | null;
  /**
   * When the current rebind window started.
   */
  rebindWindowStartedAt?: string | null;
  status: 'trial' | 'active' | 'lapsed' | 'maintenance_expired' | 'suspended' | 'cancelled';
  trialStartedAt?: string | null;
  trialEndsAt?: string | null;
  paidAt?: string | null;
  /**
   * Last paid maintenance year covers updates up to this date.
   */
  maintenanceUntil?: string | null;
  /**
   * Max desktop major version this license can install. Bump when customer pays for major upgrade.
   */
  majorVersionCap?: number | null;
  /**
   * KES one-time fee actually paid (snapshot, not current list price).
   */
  priceFeePaid?: number | null;
  /**
   * KES per-year maintenance paid (snapshot).
   */
  priceMaintenancePaid?: number | null;
  currency?: string | null;
  cloudBackupEnabled?: boolean | null;
  cloudBackupExpiresAt?: string | null;
  /**
   * Empty = system-issued (Paystack webhook). Otherwise the staff member who created it.
   */
  issuedBy?: (number | null) | User;
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Active desktop installs. One license has many machines (up to maxMachines).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines".
 */
export interface Machine {
  id: number;
  /**
   * Hardware fingerprint (CPU + motherboard + disk hash). Generated by the desktop app.
   */
  machineId: string;
  /**
   * Hashed bearer token used by the desktop app for telemetry calls.
   */
  authToken: string;
  license: number | License;
  hostname?: string | null;
  os?: ('windows' | 'linux' | 'macos') | null;
  osVersion?: string | null;
  arch?: ('x86_64' | 'aarch64') | null;
  /**
   * Semver, e.g. "0.1.6".
   */
  currentVersion?: string | null;
  activeModule?: ('core' | 'dawa' | 'retail') | null;
  /**
   * Self-reported by user during setup.
   */
  branchName?: string | null;
  productCount?: number | null;
  employeeCount?: number | null;
  salesCountLast30d?: number | null;
  salesValueLast30d?: number | null;
  lastSyncAt?: string | null;
  firstSeenAt?: string | null;
  lastSeenAt?: string | null;
  /**
   * Used only for city-level geolocation. Not displayed to customers.
   */
  lastIp?: string | null;
  lat?: number | null;
  lng?: number | null;
  city?: string | null;
  county?: string | null;
  networkMode?: ('standalone' | 'lan_master' | 'lan_client') | null;
  lanPeers?:
    | {
        peerMachineId?: string | null;
        role?: ('master' | 'client') | null;
        id?: string | null;
      }[]
    | null;
  integrations?: {
    etimsConfigured?: boolean | null;
    mpesaConfigured?: boolean | null;
    paystackConfigured?: boolean | null;
    shaConfigured?: boolean | null;
  };
  status?: ('active' | 'idle' | 'offline' | 'deactivated') | null;
  deactivatedAt?: string | null;
  deactivationReason?: ('user_initiated' | 'license_revoked' | 'replaced') | null;
  /**
   * Owner-toggled. On next heartbeat the desktop app pulls a diagnostic dump and clears this flag.
   */
  requestDiagnostic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only licensing event log (activate / validate / rebind / reject).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activations".
 */
export interface Activation {
  id: number;
  /**
   * Empty when the key did not resolve to a known license.
   */
  license?: (number | null) | License;
  machine?: (number | null) | Machine;
  /**
   * Hardware fingerprint presented by the client.
   */
  machineId?: string | null;
  event: 'activate' | 'validate' | 'rebind' | 'deactivate';
  outcome: 'success' | 'rejected_seats' | 'rejected_cooldown' | 'rejected_invalid' | 'rejected_revoked';
  /**
   * Human-readable reason / error string.
   */
  detail?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Desktop installer versions. Auto-created by CI; published manually unless autoPublish is on.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  /**
   * Semver. Set by CI from the git tag, e.g. "0.2.0", "1.0.0-beta.2".
   */
  version: string;
  /**
   * First number from version. Used to enforce per-license major-version cap.
   */
  majorVersion: number;
  channel?: ('stable' | 'beta' | 'alpha') | null;
  /**
   * e.g. "v0.2.0". Diagnostic only.
   */
  gitTag?: string | null;
  status: 'draft' | 'published' | 'rolled_back' | 'archived';
  windowsMsiUrl?: string | null;
  windowsNsisUrl?: string | null;
  /**
   * Bytes.
   */
  windowsMsiSize?: number | null;
  windowsNsisSize?: number | null;
  /**
   * Tauri updater signature for the NSIS bundle.
   */
  updaterSignature?: string | null;
  sha256Msi?: string | null;
  sha256Nsis?: string | null;
  /**
   * e.g. "v0.2.0 — Banking & Recurring Invoices".
   */
  title?: string | null;
  /**
   * One-paragraph summary, shown on changelog page.
   */
  summary?: string | null;
  /**
   * Full changelog. Markdown-style rich text.
   */
  changelog?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Lucide icon name (e.g. "ShoppingCart").
         */
        icon?: string | null;
        screenshot?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  breaking?:
    | {
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  requiresMigration?: boolean | null;
  migrationNotes?: string | null;
  /**
   * Customers with majorVersionCap below this cannot install — they need the major upgrade.
   */
  minMajorVersionToUpgrade?: number | null;
  /**
   * When on, trial users cannot install this version. Default off so trials always get latest.
   */
  requiresPaidLicense?: boolean | null;
  downloadCount?: number | null;
  installCount?: number | null;
  publishedAt?: string | null;
  publishedBy?: (number | null) | User;
  rolledBackAt?: string | null;
  rolledBackReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Anonymous diagnostic events from desktop installs. No business data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "telemetry-events".
 */
export interface TelemetryEvent {
  id: number;
  machine: number | Machine;
  eventType:
    | 'app_started'
    | 'app_closed'
    | 'heartbeat'
    | 'sync_completed'
    | 'sale_completed'
    | 'license_validated'
    | 'license_invalid'
    | 'license_expired'
    | 'crash'
    | 'panic'
    | 'db_error'
    | 'migration_error'
    | 'integration_error'
    | 'updater_check'
    | 'updater_download'
    | 'updater_installed'
    | 'manual_diagnostic'
    | 'feedback_submitted';
  severity?: ('debug' | 'info' | 'warn' | 'error' | 'fatal') | null;
  appVersion?: string | null;
  message?: string | null;
  stackTrace?: string | null;
  /**
   * Arbitrary structured data. Sanitiser on the desktop side strips anything resembling business data before sending.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sessionId?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Paystack transactions. Source of truth for all revenue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  paystackReference: string;
  paystackTransactionId?: string | null;
  customer: number | Customer;
  license?: (number | null) | License;
  /**
   * Total charged, in the currency below.
   */
  amount: number;
  currency?: string | null;
  paystackFees?: number | null;
  /**
   * Amount minus Paystack fees.
   */
  netAmount?: number | null;
  channel?: ('card' | 'mpesa' | 'bank_transfer' | 'apple_pay' | 'mobile_money') | null;
  mpesaReceiptNumber?: string | null;
  cardLast4?: string | null;
  cardBrand?: string | null;
  purpose: 'license_fee' | 'maintenance_renewal' | 'major_upgrade' | 'cloud_backup' | 'extra_branch' | 'extra_machine';
  status: 'pending' | 'success' | 'failed' | 'reversed' | 'refunded';
  failureReason?: string | null;
  refundedAt?: string | null;
  refundReason?: string | null;
  refundedBy?: (number | null) | User;
  paidAt?: string | null;
  /**
   * Full Paystack payload for forensics.
   */
  rawWebhookPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer-raised support requests. Owner + support reply in-thread.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets".
 */
export interface SupportTicket {
  id: number;
  /**
   * Auto-generated. Format: OMNIX-T-YYYY-NNNNNN.
   */
  ticketNumber?: string | null;
  customer: number | Customer;
  license?: (number | null) | License;
  machine?: (number | null) | Machine;
  subject: string;
  category?: ('bug' | 'feature_request' | 'question' | 'billing' | 'data_recovery' | 'install_help' | 'other') | null;
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  status?: ('new' | 'in_progress' | 'awaiting_customer' | 'resolved' | 'closed') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  attachments?:
    | {
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Set when customer attached a manual diagnostic dump.
   */
  attachedDiagnosticId?: (number | null) | TelemetryEvent;
  thread?:
    | {
        sender?: ('customer' | 'support' | 'owner' | 'system') | null;
        senderName?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        attachments?:
          | {
              file?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        sentAt?: string | null;
        id?: string | null;
      }[]
    | null;
  assignedTo?: (number | null) | User;
  resolvedAt?: string | null;
  /**
   * Customer rating after ticket closure (1–5 stars).
   */
  satisfactionRating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment, e.g. "privacy" → /privacy.
   */
  slug: string;
  kind?: ('legal' | 'help' | 'about' | 'compare') | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Manually set after each editorial review pass.
   */
  lastReviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('product' | 'industry' | 'tutorial' | 'announcement') | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  moduleId: 'core' | 'dawa' | 'retail' | 'hardware' | 'hospitality';
  /**
   * Display name, e.g. "Dawa Pharmacy".
   */
  name: string;
  /**
   * e.g. "Dawa". Used on cards.
   */
  shortName: string;
  /**
   * e.g. "Run your pharmacy. Calm and compliant."
   */
  tagline: string;
  available?: ('live' | 'beta' | 'planned') | null;
  /**
   * Lower number sorts first on /modules.
   */
  priority?: number | null;
  gradient?: ('amber' | 'teal' | 'orange' | 'blue' | 'pink') | null;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Lucide icon name.
         */
        icon?: string | null;
        screenshot?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  screenshots?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  targetCustomers?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  compliance?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional override; falls back to the global Pricing tier values.
   */
  pricing?: {
    starterFee?: number | null;
    businessFee?: number | null;
    maintenanceYearly?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'licenses';
        value: number | License;
      } | null)
    | ({
        relationTo: 'machines';
        value: number | Machine;
      } | null)
    | ({
        relationTo: 'activations';
        value: number | Activation;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'telemetry-events';
        value: number | TelemetryEvent;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'support-tickets';
        value: number | SupportTicket;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  businessName?: T;
  phone?: T;
  whatsapp?: T;
  kraPin?: T;
  country?: T;
  county?: T;
  town?: T;
  physicalAddress?: T;
  businessType?: T;
  employeeCount?: T;
  howDidYouHear?: T;
  newsletterOptIn?: T;
  lastSeenAt?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses_select".
 */
export interface LicensesSelect<T extends boolean = true> {
  licenseKey?: T;
  customer?: T;
  tier?: T;
  modules?: T;
  maxBranches?: T;
  maxMachines?: T;
  rebindLimitPerWindow?: T;
  rebindWindowDays?: T;
  rebindCountInWindow?: T;
  rebindWindowStartedAt?: T;
  status?: T;
  trialStartedAt?: T;
  trialEndsAt?: T;
  paidAt?: T;
  maintenanceUntil?: T;
  majorVersionCap?: T;
  priceFeePaid?: T;
  priceMaintenancePaid?: T;
  currency?: T;
  cloudBackupEnabled?: T;
  cloudBackupExpiresAt?: T;
  issuedBy?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines_select".
 */
export interface MachinesSelect<T extends boolean = true> {
  machineId?: T;
  authToken?: T;
  license?: T;
  hostname?: T;
  os?: T;
  osVersion?: T;
  arch?: T;
  currentVersion?: T;
  activeModule?: T;
  branchName?: T;
  productCount?: T;
  employeeCount?: T;
  salesCountLast30d?: T;
  salesValueLast30d?: T;
  lastSyncAt?: T;
  firstSeenAt?: T;
  lastSeenAt?: T;
  lastIp?: T;
  lat?: T;
  lng?: T;
  city?: T;
  county?: T;
  networkMode?: T;
  lanPeers?:
    | T
    | {
        peerMachineId?: T;
        role?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        etimsConfigured?: T;
        mpesaConfigured?: T;
        paystackConfigured?: T;
        shaConfigured?: T;
      };
  status?: T;
  deactivatedAt?: T;
  deactivationReason?: T;
  requestDiagnostic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activations_select".
 */
export interface ActivationsSelect<T extends boolean = true> {
  license?: T;
  machine?: T;
  machineId?: T;
  event?: T;
  outcome?: T;
  detail?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  version?: T;
  majorVersion?: T;
  channel?: T;
  gitTag?: T;
  status?: T;
  windowsMsiUrl?: T;
  windowsNsisUrl?: T;
  windowsMsiSize?: T;
  windowsNsisSize?: T;
  updaterSignature?: T;
  sha256Msi?: T;
  sha256Nsis?: T;
  title?: T;
  summary?: T;
  changelog?: T;
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        screenshot?: T;
        id?: T;
      };
  breaking?:
    | T
    | {
        description?: T;
        id?: T;
      };
  requiresMigration?: T;
  migrationNotes?: T;
  minMajorVersionToUpgrade?: T;
  requiresPaidLicense?: T;
  downloadCount?: T;
  installCount?: T;
  publishedAt?: T;
  publishedBy?: T;
  rolledBackAt?: T;
  rolledBackReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "telemetry-events_select".
 */
export interface TelemetryEventsSelect<T extends boolean = true> {
  machine?: T;
  eventType?: T;
  severity?: T;
  appVersion?: T;
  message?: T;
  stackTrace?: T;
  metadata?: T;
  sessionId?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  paystackReference?: T;
  paystackTransactionId?: T;
  customer?: T;
  license?: T;
  amount?: T;
  currency?: T;
  paystackFees?: T;
  netAmount?: T;
  channel?: T;
  mpesaReceiptNumber?: T;
  cardLast4?: T;
  cardBrand?: T;
  purpose?: T;
  status?: T;
  failureReason?: T;
  refundedAt?: T;
  refundReason?: T;
  refundedBy?: T;
  paidAt?: T;
  rawWebhookPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets_select".
 */
export interface SupportTicketsSelect<T extends boolean = true> {
  ticketNumber?: T;
  customer?: T;
  license?: T;
  machine?: T;
  subject?: T;
  category?: T;
  priority?: T;
  status?: T;
  description?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  attachedDiagnosticId?: T;
  thread?:
    | T
    | {
        sender?: T;
        senderName?: T;
        body?: T;
        attachments?:
          | T
          | {
              file?: T;
              id?: T;
            };
        sentAt?: T;
        id?: T;
      };
  assignedTo?: T;
  resolvedAt?: T;
  satisfactionRating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  lastReviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  moduleId?: T;
  name?: T;
  shortName?: T;
  tagline?: T;
  available?: T;
  priority?: T;
  gradient?: T;
  shortDescription?: T;
  longDescription?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        screenshot?: T;
        id?: T;
      };
  screenshots?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  targetCustomers?:
    | T
    | {
        label?: T;
        id?: T;
      };
  compliance?:
    | T
    | {
        item?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        starterFee?: T;
        businessFee?: T;
        maintenanceYearly?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site settings, contact channels, social links, feature flags.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Read-only — set in code via src/lib/brand.ts.
   */
  brandName?: string | null;
  tagline?: string | null;
  supportEmail?: string | null;
  salesEmail?: string | null;
  /**
   * Full international format, e.g. +254712345678. Used in wa.me links.
   */
  whatsappNumber?: string | null;
  phoneNumber?: string | null;
  office?: {
    address?: string | null;
    mapEmbedUrl?: string | null;
    workingHours?: string | null;
  };
  social?: {
    twitter?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    github?: string | null;
  };
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  footerCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown in footer for trust signal.
   */
  kraPin?: string | null;
  flags?: {
    allowSelfSignup?: boolean | null;
    allowSelfServeCheckout?: boolean | null;
    showBetaModules?: boolean | null;
    showPricing?: boolean | null;
    maintenanceMode?: boolean | null;
    /**
     * When on, CI-created releases skip "draft" and publish immediately. Default ON.
     */
    autoPublishReleases?: boolean | null;
  };
  trialLockoutMode?: ('soft' | 'readonly' | 'hard') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tier prices, add-ons, trial length, and the comparison table.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  currency?: string | null;
  trialDays?: number | null;
  starter?: {
    oneTimeFee?: number | null;
    maintenanceYearly?: number | null;
    maxBranches?: number | null;
    maxMachines?: number | null;
    features?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  business?: {
    oneTimeFee?: number | null;
    maintenanceYearly?: number | null;
    maxBranches?: number | null;
    maxMachines?: number | null;
    features?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  enterprise?: {
    /**
     * String shown instead of a number ("Contact us", "Custom", etc.).
     */
    priceLabel?: string | null;
    features?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cloudBackupMonthly?: number | null;
  extraBranchOneTime?: number | null;
  extraMachineOneTime?: number | null;
  /**
   * Percent off the new major version fee for existing license holders.
   */
  majorUpgradeDiscount?: number | null;
  compareTable?:
    | {
        feature?: string | null;
        /**
         * "✓", "✗", "1 branch" — free-text cell.
         */
        starter?: string | null;
        business?: string | null;
        enterprise?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /  landing page. Hero, modules teaser, feature spotlights, testimonials, closing CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  hero: {
    /**
     * Pill above the headline. Often links to /changelog.
     */
    eyebrow?: string | null;
    headline: string;
    subheadline?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    screenshotPosition?: ('below' | 'right' | 'bento') | null;
    screenshot?: (number | null) | Media;
  };
  /**
   * Customer logos. Leave empty until we have real customers — then the section auto-hides.
   */
  logoCloud?:
    | {
        name?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  modulesSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
  };
  featuresBento?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        span?: ('1' | '2' | '3') | null;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        quote?: string | null;
        name?: string | null;
        role?: string | null;
        businessName?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  closingCta?: {
    headline?: string | null;
    subheadline?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  supportEmail?: T;
  salesEmail?: T;
  whatsappNumber?: T;
  phoneNumber?: T;
  office?:
    | T
    | {
        address?: T;
        mapEmbedUrl?: T;
        workingHours?: T;
      };
  social?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        youtube?: T;
        github?: T;
      };
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  footerCopy?: T;
  kraPin?: T;
  flags?:
    | T
    | {
        allowSelfSignup?: T;
        allowSelfServeCheckout?: T;
        showBetaModules?: T;
        showPricing?: T;
        maintenanceMode?: T;
        autoPublishReleases?: T;
      };
  trialLockoutMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  currency?: T;
  trialDays?: T;
  starter?:
    | T
    | {
        oneTimeFee?: T;
        maintenanceYearly?: T;
        maxBranches?: T;
        maxMachines?: T;
        features?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  business?:
    | T
    | {
        oneTimeFee?: T;
        maintenanceYearly?: T;
        maxBranches?: T;
        maxMachines?: T;
        features?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  enterprise?:
    | T
    | {
        priceLabel?: T;
        features?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  cloudBackupMonthly?: T;
  extraBranchOneTime?: T;
  extraMachineOneTime?: T;
  majorUpgradeDiscount?: T;
  compareTable?:
    | T
    | {
        feature?: T;
        starter?: T;
        business?: T;
        enterprise?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        screenshotPosition?: T;
        screenshot?: T;
      };
  logoCloud?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  modulesSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
      };
  featuresBento?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        span?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        businessName?: T;
        photo?: T;
        id?: T;
      };
  closingCta?:
    | T
    | {
        headline?: T;
        subheadline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}