// License verification module
// Validates RSA-signed license keys issued by the SokoOS licensing server.

use rsa::{pkcs1v15::VerifyingKey, pkcs8::DecodePublicKey, RsaPublicKey};
use rsa::signature::Verifier;
use rsa::pkcs1v15::Signature;
use sha2::Sha256;
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use serde::{Deserialize, Serialize};
use sha2::Digest;

/// Embedded public key (PEM). Replace with production key before release.
const LICENSE_PUBLIC_KEY_PEM: &str = include_str!("../../../keys/license-public.pem");

/// License payload — what the server signs and embeds in the key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicensePayload {
    pub kid: String,                 // license key ID (human-readable, e.g., "SOKO-2026-A1B2-C3D4")
    pub name: String,                // customer/business name
    pub email: String,               // customer email
    pub issued: String,              // ISO date
    pub maint_exp: String,           // maintenance expiry ISO date (when updates stop being free)
    #[serde(rename = "type")]
    pub license_type: String,        // "perpetual" | "trial" | "subscription"
    pub feat: Vec<String>,           // enabled features
    pub ver: u32,                    // payload schema version
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifiedLicense {
    pub payload: LicensePayload,
    pub raw_key: String,             // the original key string (to store)
}

#[derive(Debug, thiserror::Error)]
pub enum LicenseError {
    #[error("Invalid license key format")]
    InvalidFormat,
    #[error("Failed to decode license payload: {0}")]
    DecodeError(String),
    #[error("License signature verification failed")]
    SignatureInvalid,
    #[error("Failed to load public key: {0}")]
    PublicKeyError(String),
    #[error("Machine fingerprint mismatch")]
    MachineMismatch,
}

/// Verify a license key string and return the decoded payload.
///
/// Format: `SOKO-<base64url(json)>.<base64url(rsa_signature)>`
pub fn verify_license_key(key: &str) -> Result<VerifiedLicense, LicenseError> {
    let key = key.trim();
    let key_body = key.strip_prefix("SOKO-").unwrap_or(key);

    let parts: Vec<&str> = key_body.split('.').collect();
    if parts.len() != 2 {
        return Err(LicenseError::InvalidFormat);
    }

    let payload_b64 = parts[0];
    let sig_b64 = parts[1];

    let payload_bytes = URL_SAFE_NO_PAD
        .decode(payload_b64)
        .map_err(|e| LicenseError::DecodeError(format!("payload b64: {}", e)))?;

    let sig_bytes = URL_SAFE_NO_PAD
        .decode(sig_b64)
        .map_err(|e| LicenseError::DecodeError(format!("sig b64: {}", e)))?;

    let payload: LicensePayload = serde_json::from_slice(&payload_bytes)
        .map_err(|e| LicenseError::DecodeError(format!("json: {}", e)))?;

    // Verify RSA signature
    let pk = RsaPublicKey::from_public_key_pem(LICENSE_PUBLIC_KEY_PEM)
        .map_err(|e| LicenseError::PublicKeyError(e.to_string()))?;

    let verifying_key: VerifyingKey<Sha256> = VerifyingKey::new(pk);
    let signature = Signature::try_from(sig_bytes.as_slice())
        .map_err(|_| LicenseError::SignatureInvalid)?;

    verifying_key
        .verify(&payload_bytes, &signature)
        .map_err(|_| LicenseError::SignatureInvalid)?;

    Ok(VerifiedLicense {
        payload,
        raw_key: key.to_string(),
    })
}

/// Compute a stable machine fingerprint.
///
/// Combines: machine UUID + first MAC address + CPU brand
/// Returns hex SHA-256 truncated to 16 chars (good enough as ID).
pub fn get_machine_fingerprint() -> String {
    let machine_uuid = machine_uid::get().unwrap_or_else(|_| "unknown".to_string());

    let mut sys = sysinfo::System::new();
    sys.refresh_cpu_all();
    let cpu_brand = sys
        .cpus()
        .first()
        .map(|c| c.brand().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    let combined = format!("{}|{}", machine_uuid, cpu_brand);
    let hash = sha2::Sha256::digest(combined.as_bytes());
    hex::encode(&hash[..8]).to_uppercase()
}

/// Format the machine fingerprint for display (groups of 4)
pub fn format_fingerprint(fp: &str) -> String {
    fp.chars()
        .collect::<Vec<_>>()
        .chunks(4)
        .map(|chunk| chunk.iter().collect::<String>())
        .collect::<Vec<_>>()
        .join("-")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A real license key generated by scripts/generate-license.mjs against keys/license-private.pem.
    /// If the keypair is regenerated, this test will fail and must be updated.
    const VALID_TEST_KEY: &str = "SOKO-eyJraWQiOiJTT0tPLTIwMjYtWkZSWi05NFo0IiwibmFtZSI6IkludGVncmF0aW9uIFRlc3QiLCJlbWFpbCI6InRlc3RAaW50ZWdyYXRpb24ubG9jYWwiLCJpc3N1ZWQiOiIyMDI2LTA1LTI1IiwibWFpbnRfZXhwIjoiMjAyNy0wNS0yNSIsInR5cGUiOiJwZXJwZXR1YWwiLCJmZWF0IjpbInBoYXJtYWN5IiwiZXRpbXMiLCJpbnN1cmFuY2UiLCJsYW4iLCJyZXBvcnRzIl0sInZlciI6MX0.mfKvN1ppsDGIwD47BXC_jLlAaGJf8_WpzWOZetL-aoivF5wEi2lzO4ux13gFNB22oYDIOsltzsEXmZ55OplDH-cftvmyGnURiCS45UZ9cwl1uSUx3UmKzgf4sJzyo5Y8A-clkDJu6IuckIXGzAHg8kW7651V5jFHo7YY0cQ_dokZCM9y9lnlDKgan3egN74UvlniWwWWJXhGp7csiSV6V4u4MOLdS0Ycx698PzmhsIQO9mWhuL-IiyaRhft3seOKU4CI07wTDkfZwh88BIYlRPwNJ2u_McV2estEKQ7T2vuioxMOwy1lOK8ZYokBWCsYhn9QbTYtgajFjMuIE6v6Sw";

    #[test]
    fn rejects_garbage() {
        assert!(verify_license_key("not-a-license").is_err());
        assert!(verify_license_key("SOKO-aaa.bbb").is_err());
        assert!(verify_license_key("").is_err());
    }

    #[test]
    fn rejects_tampered_payload() {
        // Valid format but signature won't verify against a fake payload
        let bad = "SOKO-eyJraWQiOiJ0YW1wZXJlZCIsIm5hbWUiOiJoYWNrZXIifQ.AAAA";
        assert!(matches!(
            verify_license_key(bad),
            Err(LicenseError::SignatureInvalid) | Err(LicenseError::DecodeError(_))
        ));
    }

    #[test]
    fn accepts_real_signed_key() {
        let result = verify_license_key(VALID_TEST_KEY);
        let verified = result.expect("real generated key must verify");
        assert_eq!(verified.payload.name, "Integration Test");
        assert_eq!(verified.payload.email, "test@integration.local");
        assert_eq!(verified.payload.license_type, "perpetual");
        assert!(verified.payload.feat.contains(&"pharmacy".to_string()));
    }

    #[test]
    fn rejects_mutated_signature() {
        // Take a valid key but flip one character in the signature
        let mut chars: Vec<char> = VALID_TEST_KEY.chars().collect();
        let last_idx = chars.len() - 1;
        chars[last_idx] = if chars[last_idx] == 'A' { 'B' } else { 'A' };
        let mutated: String = chars.into_iter().collect();
        assert!(matches!(
            verify_license_key(&mutated),
            Err(LicenseError::SignatureInvalid)
        ));
    }

    #[test]
    fn machine_fingerprint_is_stable() {
        let fp1 = get_machine_fingerprint();
        let fp2 = get_machine_fingerprint();
        assert_eq!(fp1, fp2);
        assert_eq!(fp1.len(), 16);
    }

    #[test]
    fn format_fingerprint_groups_in_4s() {
        assert_eq!(format_fingerprint("ABCD1234EFGH5678"), "ABCD-1234-EFGH-5678");
    }
}
