/**
 * Complete Next.js App Router inventory for the Omnix website.
 *
 * This is a redesign/regression contract, not navigation configuration.
 * The matching integration test walks src/app and fails whenever a page or
 * route handler is added, removed, or moved without being classified here.
 */

export const PAGE_ROUTE_GROUPS = {
  marketing: [
    '/[locale]',
    '/[locale]/about',
    '/[locale]/ai',
    '/[locale]/blog',
    '/[locale]/blog/[slug]',
    '/[locale]/changelog',
    '/[locale]/contact',
    '/[locale]/dawa',
    '/[locale]/developers',
    '/[locale]/docs',
    '/[locale]/docs/[slug]',
    '/[locale]/downloads',
    '/[locale]/etims',
    '/[locale]/guides',
    '/[locale]/guides/[slug]',
    '/[locale]/hardware',
    '/[locale]/hospitality',
    '/[locale]/locations',
    '/[locale]/locations/[slug]',
    '/[locale]/migration',
    '/[locale]/modules',
    '/[locale]/modules/[slug]',
    '/[locale]/mpesa',
    '/[locale]/partners',
    '/[locale]/payroll-pack',
    '/[locale]/pharmacy',
    '/[locale]/pricing',
    '/[locale]/privacy',
    '/[locale]/pro',
    '/[locale]/refund-policy',
    '/[locale]/retail',
    '/[locale]/roadmap',
    '/[locale]/salon',
    '/[locale]/security',
    '/[locale]/sha',
    '/[locale]/support',
    '/[locale]/team',
    '/[locale]/terms',
  ],
  auth: [
    '/accept-invitation/[id]',
    '/forgot-password',
    '/login',
    '/signup',
    '/verify-email/[token]',
  ],
  onboarding: ['/onboarding'],
  checkout: [
    '/buy',
    '/buy/[licenseId]',
    '/buy/cancelled',
    '/buy/success',
  ],
  region: ['/region-unavailable'],
  dashboard: [
    '/dashboard',
    '/dashboard/affiliate',
    '/dashboard/billing',
    '/dashboard/downloads',
    '/dashboard/downloads/[variant]',
    '/dashboard/licenses',
    '/dashboard/licenses/[id]',
    '/dashboard/machines',
    '/dashboard/machines/[id]',
    '/dashboard/payments',
    '/dashboard/payments/[id]',
    '/dashboard/profile',
    '/dashboard/reseller',
    '/dashboard/reseller/new',
    '/dashboard/support',
    '/dashboard/support/[id]',
    '/dashboard/support/new',
    '/dashboard/team',
  ],
  admin: [
    '/admin',
    '/admin/audit',
    '/admin/audit/[id]',
    '/admin/customers/new',
    '/admin/licenses',
    '/admin/licenses/[id]',
    '/admin/machines',
    '/admin/machines/[id]',
    '/admin/media',
    '/admin/module-videos',
    '/admin/orgs',
    '/admin/orgs/[id]',
    '/admin/payments',
    '/admin/payments/[id]',
    '/admin/releases',
    '/admin/settings',
    '/admin/team',
    '/admin/team/[id]',
    '/admin/team-members',
    '/admin/tickets',
    '/admin/tickets/[id]',
    '/admin/users',
    '/admin/users/[id]',
  ],
} as const satisfies Record<string, readonly string[]>

export const API_ROUTE_GROUPS = {
  platformAdmin: [
    '/api/admin/customers',
    '/api/admin/licenses/[id]',
    '/api/admin/licenses/[id]/mark-paid',
    '/api/admin/licenses/[id]/sweep-orphans',
    '/api/admin/machines/[id]/update-policy',
    '/api/admin/media',
    '/api/admin/module-videos',
    '/api/admin/promote',
    '/api/admin/releases/sync-from-github',
    '/api/admin/settings',
    '/api/admin/settings/generate',
    '/api/admin/settings/import-env',
    '/api/admin/settings/test',
    '/api/admin/team',
    '/api/admin/team/[id]',
    '/api/admin/team/[id]/resend',
    '/api/admin/team-members',
    '/api/admin/users/[id]/reseller',
  ],
  account: [
    '/api/affiliate',
    '/api/auth/[...all]',
    '/api/customers/me',
    '/api/dashboard/licenses/[id]',
    '/api/dashboard/machines/[id]',
    '/api/dashboard/team/invitations',
    '/api/dashboard/team/invitations/[id]',
    '/api/dashboard/trial',
    '/api/paystack/init',
    '/api/reseller/issue-license',
    '/api/support/tickets',
  ],
  paymentCallback: ['/api/paystack/webhook'],
  desktop: [
    '/api/cloud-backup/list',
    '/api/licensing/activate',
    '/api/licensing/sync',
    '/api/licensing/validate',
    '/api/licenses/activate',
    '/api/licenses/rebind',
    '/api/licenses/validate',
    '/api/telemetry/heartbeat',
    '/api/trials/start',
    '/api/updater/gate',
  ],
  releases: [
    '/api/releases-latest',
    '/api/releases-sync',
    '/api/releases/latest',
  ],
  publicApi: [
    '/api/public/v1/health',
    '/api/public/v1/licenses',
    '/api/public/v1/machines',
  ],
  operations: [
    '/api/bootstrap-db',
    '/api/bootstrap-email',
    '/api/cron/daily',
    '/api/cron/telemetry-retention',
    '/api/migrate-db',
  ],
  publicSite: [
    '/api/demo-requests',
    '/api/og',
    '/api/partnerships',
  ],
} as const satisfies Record<string, readonly string[]>

function flattenAndSort(groups: Record<string, readonly string[]>): string[] {
  return Object.values(groups).flat().sort()
}

export const APP_PAGE_ROUTES = flattenAndSort(PAGE_ROUTE_GROUPS)
export const APP_API_ROUTES = flattenAndSort(API_ROUTE_GROUPS)
