import type { CollectionConfig } from 'payload'
import { allowSystem, ownerOnly } from '../access'

/**
 * Machines — every install of the desktop app.
 * Joined to Licenses; telemetry events join here.
 *
 * Self-registered by the desktop app on first activation. The auth token
 * stored here is hashed (never plain) and matched on every telemetry POST.
 */
export const Machines: CollectionConfig = {
  slug: 'machines',
  admin: {
    useAsTitle: 'hostname',
    defaultColumns: ['hostname', 'license', 'os', 'currentVersion', 'lastSeenAt'],
    description: 'Active desktop installs. One license has many machines (up to maxMachines).',
  },
  access: {
    read: ({ req }) => {
      if (req.user?.collection === 'users') return true
      // Customer dashboard pages (overview, /machines list, /machines/[id])
      // need to read their own machines via Payload local-API. Scope strictly
      // by license.customer = req.user.id so customers can never read another
      // customer's machines.
      if (req.user?.collection === 'customers') {
        return {
          'license.customer': { equals: req.user.id },
        }
      }
      return false
    },
    create: ({ req }) => allowSystem(req) || ownerOnly({ req } as never) === true,
    update: ({ req }) => allowSystem(req) || ownerOnly({ req } as never) === true,
    delete: ownerOnly,
  },
  fields: [
    {
      name: 'machineId',
      type: 'text',
      required: true,
      unique: true,
      admin: { description: 'Hardware fingerprint (CPU + motherboard + disk hash). Generated by the desktop app.' },
    },
    {
      name: 'authToken',
      type: 'text',
      required: true,
      admin: { hidden: true, description: 'Hashed bearer token used by the desktop app for telemetry calls.' },
    },
    {
      name: 'license',
      type: 'relationship',
      relationTo: 'licenses',
      required: true,
    },

    // ── Identity ────────────────────────────────────────────────
    { name: 'hostname', type: 'text' },
    {
      name: 'os',
      type: 'select',
      defaultValue: 'windows',
      options: [
        { label: 'Windows', value: 'windows' },
        { label: 'Linux', value: 'linux' },
        { label: 'macOS', value: 'macos' },
      ],
    },
    { name: 'osVersion', type: 'text' },
    {
      name: 'arch',
      type: 'select',
      options: [
        { label: 'x86_64', value: 'x86_64' },
        { label: 'aarch64 (ARM)', value: 'aarch64' },
      ],
    },

    // ── App state ──────────────────────────────────────────────
    { name: 'currentVersion', type: 'text', admin: { description: 'Semver, e.g. "0.1.6".' } },
    {
      name: 'activeModule',
      type: 'select',
      options: [
        { label: 'Core ERP', value: 'core' },
        { label: 'Dawa Pharmacy', value: 'dawa' },
        { label: 'Soko Retail', value: 'retail' },
      ],
    },
    { name: 'branchName', type: 'text', admin: { description: 'Self-reported by user during setup.' } },

    // ── Telemetry rollups (denormalised for fast admin display) ─
    { name: 'productCount', type: 'number' },
    { name: 'employeeCount', type: 'number' },
    { name: 'salesCountLast30d', type: 'number' },
    { name: 'salesValueLast30d', type: 'number' },
    {
      name: 'currency',
      type: 'select',
      defaultValue: 'KES',
      options: ['KES', 'USD', 'NGN', 'GHS', 'ZAR', 'TZS', 'UGX', 'RWF', 'EGP', 'INR', 'GBP', 'EUR', 'AED', 'ZMW', 'XAF', 'XOF'],
      admin: {
        description: 'Currency the desktop app reports sales in — sent on every telemetry heartbeat. Drives the currency prefix on machine detail pages.',
      },
    },
    { name: 'lastSyncAt', type: 'date' },
    { name: 'firstSeenAt', type: 'date' },
    { name: 'lastSeenAt', type: 'date' },

    // ── Geo ────────────────────────────────────────────────────
    { name: 'lastIp', type: 'text', admin: { description: 'Used only for city-level geolocation. Not displayed to customers.' } },
    { name: 'lat', type: 'number' },
    { name: 'lng', type: 'number' },
    { name: 'city', type: 'text' },
    { name: 'county', type: 'text' },

    // ── Network mode ───────────────────────────────────────────
    {
      name: 'networkMode',
      type: 'select',
      options: [
        { label: 'Standalone', value: 'standalone' },
        { label: 'LAN master', value: 'lan_master' },
        { label: 'LAN client', value: 'lan_client' },
      ],
    },
    {
      name: 'lanPeers',
      type: 'array',
      fields: [
        { name: 'peerMachineId', type: 'text' },
        {
          name: 'role',
          type: 'select',
          options: [
            { label: 'Master', value: 'master' },
            { label: 'Client', value: 'client' },
          ],
        },
      ],
    },

    // ── Integration status ─────────────────────────────────────
    {
      name: 'integrations',
      type: 'group',
      fields: [
        { name: 'etimsConfigured', type: 'checkbox' },
        { name: 'mpesaConfigured', type: 'checkbox' },
        { name: 'paystackConfigured', type: 'checkbox' },
        { name: 'shaConfigured', type: 'checkbox' },
      ],
    },

    // ── Health ─────────────────────────────────────────────────
    {
      name: 'status',
      type: 'select',
      defaultValue: 'active',
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Idle', value: 'idle' },
        { label: 'Offline', value: 'offline' },
        { label: 'Deactivated', value: 'deactivated' },
      ],
    },
    { name: 'deactivatedAt', type: 'date' },
    {
      name: 'deactivationReason',
      type: 'select',
      options: [
        { label: 'User-initiated', value: 'user_initiated' },
        { label: 'License revoked', value: 'license_revoked' },
        { label: 'Replaced (new hardware)', value: 'replaced' },
      ],
    },

    // ── Owner-driven flags ─────────────────────────────────────
    {
      name: 'requestDiagnostic',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        description: 'Owner-toggled. On next heartbeat the desktop app pulls a diagnostic dump and clears this flag.',
      },
    },
  ],
}
