'use client'

import { motion } from 'motion/react'
import Link from 'next/link'

/**
 * "The reports too." — proof-of-output grid.
 *
 * Shows six real PDFs the app generates, each linking to a downloadable
 * sample in /public/samples/ produced by tests/_marketing-samples.spec.ts.
 *
 * Editorial choices:
 *   - No icons (the PDF document IS the icon — let the content stand)
 *   - 3-col on desktop, 2-col on tablet, 1-col on mobile
 *   - Each tile: eyebrow (filing name) + serif title + 1-line plain
 *     description + caption row with file size + "Download sample"
 *   - Generous gutters; this is meant to read like a periodical's
 *     contents page, not a feature wall.
 */
const PDFS = [
  {
    eyebrow: 'KRA · Monthly',
    title: 'VAT3 Return',
    description:
      'Output VAT and input VAT for the period, ready to copy into iTax. Branded with your masthead and KRA PIN.',
    href: '/samples/vat3-sample.pdf',
    fileSize: '4 kB',
  },
  {
    eyebrow: 'KRA · Annual',
    title: 'P9 Tax Certificate',
    description:
      'Per-employee yearly PAYE summary with NSSF, SHIF, and Housing Levy lines.',
    href: '/samples/p9-sample.pdf',
    fileSize: '5 kB',
  },
  {
    eyebrow: 'KRA · Monthly',
    title: 'P10 PAYE Return',
    description:
      'The whole payroll batch — every employee\'s PAYE, NSSF, SHIF, Housing Levy in one PDF.',
    href: '/samples/p10-sample.pdf',
    fileSize: '5 kB',
  },
  {
    eyebrow: 'Procurement',
    title: 'Goods Received Note',
    description:
      'Itemised receipt of stock against a PO. Batch numbers, expiry dates, supplier signature line.',
    href: '/samples/grn-sample.pdf',
    fileSize: '5 kB',
  },
  {
    eyebrow: 'Sales · Quotation',
    title: 'Hardware Quotation',
    description:
      'Bulk discount, VAT line, project notes. Validity stamped on the page so customers know the lock-in.',
    href: '/samples/hardware-quote-sample.pdf',
    fileSize: '5 kB',
  },
  {
    eyebrow: 'Operations',
    title: 'Z-Report (shift close)',
    description:
      'Cash, M-Pesa, card, insurance — every payment method reconciled. Cash variance flagged.',
    href: '/samples/z-report-sample.pdf',
    fileSize: '5 kB',
  },
]

export function PdfPackSection() {
  return (
    <section className="section-tight">
      <div className="container-wide">
        <div className="mb-14 max-w-[44rem]">
          <span className="eyebrow">The reports too.</span>
          <h2 className="headline-section mt-5 text-balance">
            Every filing, <em>in your colours.</em>
          </h2>
          <p className="lede mt-6">
            Click any tile to download a real PDF sample. They&rsquo;re generated by the
            same engine the app uses on your installed copy &mdash; the only thing different
            is the business name on the masthead.
          </p>
        </div>

        <motion.ul
          initial={{ opacity: 0, y: 12 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-10%' }}
          transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
          className="grid grid-cols-1 gap-x-10 gap-y-12 md:grid-cols-2 lg:grid-cols-3"
        >
          {PDFS.map((p) => (
            <li key={p.href} className="flex flex-col gap-3 border-t border-foreground/10 pt-5">
              <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
                {p.eyebrow}
              </span>
              <h3
                style={{ fontFamily: 'var(--font-display, serif)' }}
                className="text-[24px] font-medium leading-[1.1] tracking-[-0.01em]"
              >
                {p.title}
              </h3>
              <p className="text-[14px] leading-[1.55] text-muted-foreground">{p.description}</p>
              <div className="mt-2 flex items-center justify-between">
                <Link
                  href={p.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-mono text-[11px] uppercase tracking-[0.18em] underline-offset-4 hover:underline"
                >
                  Download sample →
                </Link>
                <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground/70">
                  PDF · {p.fileSize}
                </span>
              </div>
            </li>
          ))}
        </motion.ul>

        <p className="mt-14 max-w-[44rem] text-[13px] leading-[1.6] text-muted-foreground">
          The full list runs to sixteen documents &mdash; aged receivables, dead stock,
          stock-take variance, payment mix, day book, controlled-substances register,
          insurance claims batch and more. All generated locally on your machine, all branded
          to your business, all one click.
        </p>
      </div>
    </section>
  )
}
